### ISSUE TITLE
Question about language cnn in the reference paper

### ISSUE THREAD

**Issue by vanpersie32** [lxtGH/AI_challenger_Chinese_Caption#4]
Hey, I want to know if the repository contains the implementation of language cnn for image captioning. According to the reference paper [here](https://arxiv.org/pdf/1612.07086.pdf), it outperform the encoder-decoder model baseline by a large margin. Have you notice that performance increase when using language cnn?

**Comment by vanpersie32** [comment]
Hi, may I have contact with you? I also work on image captioning project. I think we can chat with each other

**Comment by lxtGH** [comment]
No，I think that model is not the state of art.

**Comment by lxtGH** [comment]
ok

**Comment by lxtGH** [comment]
Ok, my email is xiangtai94@gmail.com

**Comment by vanpersie32** [comment]
@lxtGH But It is easy to implement and can be easily incorporated into other state of art model. According the paper, performance increase by over eight percent, it is awesome.
